In [1]:
import pandas as pd

df = pd.read_csv('sg_companies_reviews.csv')

if df['Pros'].str.contains('\n').any() or df['Cons'].str.contains('\n').any():
    print('yes')
else:
    print('no')

# df.memory_usage(deep=True)
initial_size = df.memory_usage(deep=True).sum()
df

yes

C:\Users\vinta\AppData\Local\Temp\ipykernel_6336\3388935666.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

,Company Name,Overall Rating,Review Date,Review Title,Job Title,Job Details,Location,Pros,Cons
0,Amazon,5,12-Feb-24,"Good pay, hard work",Area Manager II,"Former Employee, more than 3 years","Romulus, MI","Pay, autonomy, plenty of benefits",It was hard work in a warehouse. Many days of ...
1,Amazon,5,10-Jan-16,You Get What You Put In,Anonymous Employee,Current Employee,"Seattle, WA","Really smart people, a lot of opportunity for ...",You have to be self motivated. NO ONE will hol...
2,Amazon,3,20-Feb-16,"Exciting Work, Abusive Culture",Senior Engineering Manager,"Current Employee, more than 8 years","Seattle, WA","Jeff Bezos and his ""S-Team"" are brilliant and ...","The management process is abusive, and I'm cur..."
3,Amazon,4,17-Dec-13,"Can be amazing for some people, horrible for o...",Software Development Manager,"Current Employee, more than 3 years","Seattle, WA",Amazon is doing lot's of cool stuff...but lots...,- You're responsible for your own career progr...
4,Amazon,5,23-Feb-18,An Amazing Place to Work,Software Development Manager,"Current Employee, less than 1 year","Phoenix, AZ","I've been at Amazon for a month now, and I've ...","No cons, so far - seriously. Like I said, I'm ..."
...,...,...,...,...,...,...,...,...,...
10030,NCR,4,45215,"Good, but could be better",Customer Engineer,"Former Employee, more than 1 year","Miami, FL","Management was good, solid training, opportuni...","Inconsistent schedule, growth within the compa..."
10031,NCR,5,45222,Great starting position,Sr. Software Support Engineer,Former Employee,"Atlanta, GA",Learn a lot Develop skills,There was a lot of overtime
10032,NCR,4,45143,"Great Company, on call rotation",ATM Technician,"Former Employee, more than 1 year","Springfield, MO","Great Company. Provided a vehicle, and covered...","Lots of travel, and rotating ""On call"". Very l..."
10033,NCR,1,45282,Na,Analyst,"Former Employee, more than 3 years","Atlanta, GA",Located in midtown and nice building,"No pay increase, revolving door of managers, a..."
10034,NCR,4,45204,Good Values. Poor Compensation.,Software Engineer II,Current Employee,NaN,This is a great place to start your career and...,They have poor compensation compare to other l...

In [2]:
df.loc[4796]['Cons']

"Also, from my own perspective:\n* The expected and very common stresses and troubles you get working in an IT firm. However, Avanade does seek to take care of employees' mental health, while most other companies do not.\n* Good or bad experience dependent on the client that you are outsourced to."

In [3]:
df.replace('#NAME?', pd.NA, inplace=True) # replace '#NAME?' with NaN

print(df.shape)
# Replace '' with NaN
df.replace('', pd.NA, inplace=True) # replace '' with NaN
# df.replace('â€¢', '', inplace=True) # replace 'â€¢' with ''
# df.replace('â€™', "'", inplace=True) # replace 'â€™' with "'"
df.replace('\u2022', '', regex=True, inplace=True) # replace 'â€¢' with ''
df.replace('\u2019', "'", regex=True, inplace=True) # replace 'â€™' with "'"
df.replace('\r\n\-', ' ', regex=True, inplace=True) # replace '\r\n-' with ' '
df.replace('\r\n\*', ' ', regex=True, inplace=True) # replace '\r\n*' with ' '
df.replace('\r\nâ€¢', ' ', regex=True, inplace=True) # replace '\r\nâ€¢' with ' '
df.replace('\n\r\-', ' ', regex=True, inplace=True) # replace '\n\r-' with ' '
df.replace('\n\r\*', ' ', regex=True, inplace=True) # replace '\n\r*' with ' '
df.replace('\n\râ€¢', ' ', regex=True, inplace=True) # replace '\n\râ€¢' with ' '
df.replace('\n\-', ' ', regex=True, inplace=True) # replace '\n-' with ' '
df.replace('\n\*', '', regex=True, inplace=True) # replace '\n*' with ' '
df.replace('\nâ€¢', ' ', inplace=True) # replace '\nâ€¢' with ' '
df.replace('\r-', ' ', inplace=True) # replace '\r-' with ' '
df.replace('\r*', ' ', inplace=True) # replace '\r*' with ' '
df.replace('\râ€¢', ' ', inplace=True) # replace '\râ€¢' with ' '
df.replace('\n',' ', regex=True, inplace=True) # replace '\n' with ' '
df.replace('\r',' ', regex=True, inplace=True) # replace '\r' with ' '
df.replace('\t',' ', regex=True, inplace=True) # replace '\t' with ' '
df_dropped= df.dropna(          # drop rows with NaN in Pros or Cons
    subset=['Pros', 'Cons'], 
    inplace=False)

print(df_dropped.shape)

# # Print the rows that were dropped in both cases
# df = df[~df.index.isin(df_dropped.index)]
# df_dropped

(10035, 9)
(9550, 9)

In [4]:
df.loc[4796]['Cons']

"Also, from my own perspective: The expected and very common stresses and troubles you get working in an IT firm. However, Avanade does seek to take care of employees' mental health, while most other companies do not. Good or bad experience dependent on the client that you are outsourced to."

In [5]:
df = df_dropped
df['Pros'] = df['Pros'].map(lambda x: x.lstrip('- ') if isinstance(x, str) else x)
df['Cons'] = df['Cons'].map(lambda x: x.lstrip('- ') if isinstance(x, str) else x)
df['Pros'] = df['Pros'].map(lambda x: x.lstrip('* ') if isinstance(x, str) else x)
df['Cons'] = df['Cons'].map(lambda x: x.lstrip('* ') if isinstance(x, str) else x)
df = df.map(lambda x: x.strip() if isinstance(x, str) else x) # strip leading and trailing whitespaces from strings


if df['Pros'].str.contains('\n').any() or df['Cons'].str.contains('\n').any():
    print('yes')
else:
    print('no')

df

no

C:\Users\vinta\AppData\Local\Temp\ipykernel_6336\460495321.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pros'] = df['Pros'].map(lambda x: x.lstrip('- ') if isinstance(x, str) else x)
C:\Users\vinta\AppData\Local\Temp\ipykernel_6336\460495321.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cons'] = df['Cons'].map(lambda x: x.lstrip('- ') if isinstance(x, str) else x)
C:\Users\vinta\AppData\Local\Temp\ipykernel_6336\460495321.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pros'] = df['Pros'].map(lambda x: x.lstrip('* ') if isinstance(x, str) else x)
C:\Users\vinta\AppData\Local\Temp\ipykernel_6336\460495321.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cons'] = df['Cons'].map(lambda x: x.lstrip('* ') if isinstance(x, str) else x)

,Company Name,Overall Rating,Review Date,Review Title,Job Title,Job Details,Location,Pros,Cons
0,Amazon,5,12-Feb-24,"Good pay, hard work",Area Manager II,"Former Employee, more than 3 years","Romulus, MI","Pay, autonomy, plenty of benefits",It was hard work in a warehouse. Many days of ...
1,Amazon,5,10-Jan-16,You Get What You Put In,Anonymous Employee,Current Employee,"Seattle, WA","Really smart people, a lot of opportunity for ...",You have to be self motivated. NO ONE will hol...
2,Amazon,3,20-Feb-16,"Exciting Work, Abusive Culture",Senior Engineering Manager,"Current Employee, more than 8 years","Seattle, WA","Jeff Bezos and his ""S-Team"" are brilliant and ...","The management process is abusive, and I'm cur..."
3,Amazon,4,17-Dec-13,"Can be amazing for some people, horrible for o...",Software Development Manager,"Current Employee, more than 3 years","Seattle, WA",Amazon is doing lot's of cool stuff...but lots...,You're responsible for your own career progres...
4,Amazon,5,23-Feb-18,An Amazing Place to Work,Software Development Manager,"Current Employee, less than 1 year","Phoenix, AZ","I've been at Amazon for a month now, and I've ...","No cons, so far - seriously. Like I said, I'm ..."
...,...,...,...,...,...,...,...,...,...
10030,NCR,4,45215,"Good, but could be better",Customer Engineer,"Former Employee, more than 1 year","Miami, FL","Management was good, solid training, opportuni...","Inconsistent schedule, growth within the compa..."
10031,NCR,5,45222,Great starting position,Sr. Software Support Engineer,Former Employee,"Atlanta, GA",Learn a lot Develop skills,There was a lot of overtime
10032,NCR,4,45143,"Great Company, on call rotation",ATM Technician,"Former Employee, more than 1 year","Springfield, MO","Great Company. Provided a vehicle, and covered...","Lots of travel, and rotating ""On call"". Very l..."
10033,NCR,1,45282,Na,Analyst,"Former Employee, more than 3 years","Atlanta, GA",Located in midtown and nice building,"No pay increase, revolving door of managers, a..."
10034,NCR,4,45204,Good Values. Poor Compensation.,Software Engineer II,Current Employee,NaN,This is a great place to start your career and...,They have poor compensation compare to other l...

In [6]:
final_size = df.memory_usage(deep=True).sum()
print("Differenc:", initial_size - final_size)
df.memory_usage(deep=True)

Differenc: 445098

Index               76400
Company Name       631488
Overall Rating      76400
Review Date        599727
Review Title       763751
Job Title          726272
Job Details        809418
Location           566885
Pros              1599031
Cons              2261142
dtype: int64

In [7]:
df.to_csv('sg_companies_reviews_cleaned.csv', index=False)